In [1]:
import numpy as np

In [ ]:
# --- 3 NumPy Arrays ---

In [102]:
# 3.1 1D NumPy Arrays

list = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list)

print(arr * 4)
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
arr_min = np.argmin(arr)
arr_max = np.argmax(arr)
print(arr[arr_min])
print(arr[arr_max])
print(np.min(arr))
print(np.max(arr))

# Yes, the values for max and min match


mask1 = arr > 20
new_array = arr[mask1]
print(new_array)



[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
4
50
4
50
[27 31 50 39 35]


In [103]:
# 3.2 2D NumPy Arrays

matrix_list = [
    [5, 12, 7, 9],
    [8, 21, 14, 3],
    [6, 13, 19, 11]
]

matrix = np.array(matrix_list)


print(np.shape(matrix)) # 3 Rows and 4 Columns
print(matrix[:, 2])
print(matrix[1])
print(matrix * 2)

print(np.mean(matrix[:, 0])) # mean for 1st column
print(np.mean(matrix[:, 1])) # mean for 2nd column
print(np.mean(matrix[:, 2])) # mean for 3rd column

print(np.mean(matrix))

print(np.max(matrix[0])) # max in row 1
print(np.max(matrix[1])) # max in row 2
print(np.max(matrix[2])) # max in row 3

print(np.min(matrix[:, 0])) # min in column 1
print(np.min(matrix[:, 1])) # min in column 2
print(np.min(matrix[:, 2])) # min in column 3
print(np.min(matrix[:, 3])) # min in column 4


flat_matrix = matrix.flatten()
print(flat_matrix)
print(np.shape(flat_matrix)) # The new shape is 12 Rows, it flattened the original matrix to be one column

flat_mat_min = np.argmin(matrix)
flat_mat_max = np.argmax(matrix)
print(np.unravel_index(flat_mat_min, np.shape(matrix)))
print(np.unravel_index(flat_mat_max, np.shape(matrix)))

mask2 = matrix > 15
new_matrix = matrix[mask2]
print(new_matrix)
print(np.sort(new_matrix))

(3, 4)
[ 7 14 19]
[ 8 21 14  3]
[[10 24 14 18]
 [16 42 28  6]
 [12 26 38 22]]
6.333333333333333
15.333333333333334
13.333333333333334
10.666666666666666
12
21
19
5
12
7
3
[ 5 12  7  9  8 21 14  3  6 13 19 11]
(12,)
(np.int64(1), np.int64(3))
(np.int64(1), np.int64(1))
[21 19]
[19 21]


In [104]:
# --- 4 Prime Star Systems ---


arr = np.array([
    [2, 3, 5],
    [14, 6, 8],
    [11, 13, 17],
    [7, 10, 13]
])

def prime_row_array(matrix):
    prime_mask = []
    for row in matrix:
        for val in row:
            if (val % 2 == 0) or (val % 3 == 0):
                prime_bool = False
            else:
                prime_bool = True
        prime_mask.append(prime_bool)
    prime_matrix = matrix[prime_mask]
    return prime_matrix
    




print(prime_row_array(arr))

[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [105]:
# --- 5 Let's Play Checkers! ---


# 5.1

def eight_by_eight():
    board = np.zeros((8, 8))
    return board

board = eight_by_eight()


# 5.2

board[::2, ::2] = 1


# 5.3

board[1::2, 1::2] = 1
print(board)


# 5.4

def reverse_checkerboard(board):
    new_board = board[::-1]
    return new_board

print(reverse_checkerboard(board))

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [106]:
# --- 6 The Expanding Universe ---


universe = np.array(["galaxy", "clusters"])

number = 1

def expansion(string, number):
    new_univ = []
    
    for word in string:
        new_word = ""
        for letter in word:  
            new_letter = letter + (number * " ")
            new_word = new_word + new_letter
        new_univ.append(new_word)
    return new_univ
            

print(expansion(universe, number))

['g a l a x y ', 'c l u s t e r s ']


In [107]:
# --- 7 Second-Brightest Star ---


np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print(stars)

def secondBrightest(stars):
    secondBrightestArray = []
    for cluster in stars:
        brightestStar = np.max(cluster)
        secondBrightestStar = 0
        for star in cluster:
            if (star > secondBrightestStar) and (star != brightestStar):
                secondBrightestStar = star
        secondBrightestArray.append(secondBrightestStar)
    return np.array(secondBrightestArray)
            

print(secondBrightest(stars))


[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]
[1889 1647 1138 1863 1592]
